db:
  image: mysql
  volumes:
    - ./database/mysql:/var/lib/mysql
    - ./database/:/database
  environment:
    - MYSQL_ROOT_PASSWORD=test123
  command: "/database/run.sh"

blog:
  image: wordpress
  environment:
    - WORDPRESS_DB_PASSWORD=test123
  links:
    - db:mysql
  ports:
    - 8080:80
